#ifndef J_JOPS_H
#define J_JOPS_H

#include "mlir/IR/Dialect.h"
#include "mlir/IR/OpDefinition.h"
#include "mlir/Interfaces/InferTypeOpInterface.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"

namespace j {

/*************************** Constants ***************************************/
class ConstantOp
    : public mlir::Op<ConstantOp,
                      /// The ConstantOp takes zero input operands.
                      mlir::OpTrait::ZeroOperands,
                      /// The ConstantOp returns a single result.
                      mlir::OpTrait::OneResult,
                      /// We also provide a utility `getType` accessor that
                      /// returns the TensorType of the single result.
                      mlir::OpTrait::OneTypedResult<mlir::TensorType>::Impl> {

public:
  // yes this is redundant hence tablegen
  using OpBase =
      mlir::Op<ConstantOp,
               mlir::OpTrait::ZeroOperands,
               mlir::OpTrait::OneResult,
               mlir::OpTrait::OneTypedResult<mlir::TensorType>::Impl>;
  // 2. Use the shorthand to inherit the constructors
  using OpBase::OpBase;

  /// Provide the unique name for this operation. MLIR will use this to register
  /// the operation and uniquely identify it throughout the system. The name
  /// provided here must be prefixed by the parent dialect namespace followed
  /// by a `.`.
  static llvm::StringRef getOperationName() { return "j.constant"; }

  // This is expected by MLIR and would be generated by tablegen. In the op
  // implementation we add the "value" attribute, here we tell mlir that that
  // attribute exists
  static llvm::ArrayRef<llvm::StringRef> getAttributeNames() {
    static llvm::StringRef attrNames[] = {llvm::StringRef("value")};
    return llvm::ArrayRef(attrNames);
  }

  /// Return the value of the constant by fetching it from the attribute.
  mlir::DenseElementsAttr getValue();

  /// Operations may provide additional verification beyond what the attached
  /// traits provide.  Here we will ensure that the specific invariants of the
  /// constant operation are upheld, for example the result type must be
  /// of TensorType and matches the type of the constant `value`.
  mlir::LogicalResult verifyInvariants();

  /// Provide an interface to build this operation from a set of input values.
  /// This interface is used by the `builder` classes to allow for easily
  /// generating instances of this operation:
  ///   mlir::OpBuilder::create<ConstantOp>(...)
  /// This method populates the given `state` that MLIR uses to create
  /// operations. This state is a collection of all of the discrete elements
  /// that an operation may contain.
  /// Build a constant with the given return type and `value` attribute.
  static void build(mlir::OpBuilder &builder,
                    mlir::OperationState &state,
                    mlir::Type result,
                    mlir::DenseElementsAttr value);
  /// Build a constant and reuse the type from the given 'value'.
  static void build(mlir::OpBuilder &builder,
                    mlir::OperationState &state,
                    mlir::DenseElementsAttr value);
  /// Build a constant by broadcasting the given 'value'.
  static void
  build(mlir::OpBuilder &builder, mlir::OperationState &state, double value);
};

/*************************** BinOps *******************************************/
/// The Plus operation (+) in J.
/// In J, '+' is a dyad that performs element-wise addition.
/// It supports "Rank Agreement," but for this C++ header, we define
/// the interface for MLIR to track the operation.
/// ***** This is just to see what a handwritten op would feel like *****
class PlusOp : public mlir::Op<PlusOp, // PlusOp because CRTP
                               mlir::OpTrait::AtLeastNOperands<2>::Impl,
                               mlir::OpTrait::OneResult,
                               mlir::OpTrait::AlwaysSpeculatableImplTrait,
                               mlir::ConditionallySpeculatable::Trait,
                               mlir::MemoryEffectOpInterface::Trait> {
public:
  // Inherit constructors from the base Op class
  using OpBase = mlir::Op<PlusOp,
                          mlir::OpTrait::AtLeastNOperands<2>::Impl,
                          mlir::OpTrait::OneResult,
                          mlir::OpTrait::AlwaysSpeculatableImplTrait,
                          mlir::ConditionallySpeculatable::Trait,
                          mlir::MemoryEffectOpInterface::Trait>;

  // shorthand to inherit the constructors
  using OpBase::OpBase;
  static llvm::StringRef getOperationName() { return "j.plus"; }
  static llvm::ArrayRef<llvm::StringRef> getAttributeNames() { return {}; }

  void getEffects(llvm::SmallVectorImpl<mlir::SideEffects::EffectInstance<
                      mlir::MemoryEffects::Effect>> &effects) {
    // plus can allocate
    effects.emplace_back(mlir::MemoryEffects::Allocate::get());
  }

  static void build(mlir::OpBuilder &builder,
                    mlir::OperationState &state,
                    mlir::Value lhs,
                    mlir::Value rhs);

  // Helpers to access operands
  mlir::Value getLhs() { return getOperation()->getOperand(0); }
  mlir::Value getRhs() { return getOperation()->getOperand(1); }

  // Mandatory: Logical validation of the operation
  mlir::LogicalResult verify();
};

} // namespace j

#endif // J_JOPS_H
